### ISSUE TITLE
libtorch问题

### ISSUE THREAD

**Issue by liubamboo** [KinglittleQ/SuperPoint_SLAM#19]
您好，很感谢您的工作，请问您是在cuda多少版本下编译libtorch的呢？我目前电脑装的是cuda 9.0 ubuntu，当我按照您介绍的那样安装1.0.1的libtorch时报出了如下错误：
-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Found cuDNN: v7.5.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so.7)
CMake Error at cmake/public/cuda.cmake:330 (message):
  CUDA 9.0 is not compatible with std::tuple from GCC version >= 6.  Please
  upgrade to CUDA 9.2 or use the following option to use another version (for
  example):

    -DCUDA_HOST_COMPILER=/usr/bin/gcc-5

Call Stack (most recent call first):
  cmake/Dependencies.cmake:656 (include)
  CMakeLists.txt:201 (include)

-- Configuring incomplete, errors occurred!
See also "/home/n609/install/libtorch/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/n609/install/libtorch/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 30, in <module>
    subprocess.check_call(command, universal_newlines=True, env=my_env)
  File "/home/n609/install/Anaconda/anaconda3/envs/py36-torch110-cuda90/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/n609/install/libtorch/pytorch/tools/build_pytorch_libs.sh', '--use-cuda', '--use-nnpack', '--use-mkldnn', '--use-qnnpack', 'caffe2']' returned non-zero exit status 1.

我尝试切换gcc版本， 7.5和5.5的都试过了，但是还是会出现一样的问题，我希望可以用gpu来运行代码，请问有什么方法解决这个问题吗？

**Comment by liubamboo** [comment]
通过安装cuda 9.2, gcc切换到7.5版本，nvidia升级对应的版本的驱动解决问题
